using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace SplineMesh {
    /// <summary>
    /// Example of component to show that the spline is an independant mathematical component and can be used for other purposes than mesh deformation.
    /// 
    /// This component is only for demo purpose and is not intended to be used as-is.
    /// 
    /// We only move an object along the spline. Imagine a camera route, a ship patrol...
    /// </summary>
    [ExecuteInEditMode]
    [RequireComponent(typeof(Spline))]
    public class FollowSpline : MonoBehaviour {
        private GameObject generated;
        private Spline spline;

        public GameObject Follower;

        [Range(0, 1)]
        public float rate = 0;
        private float _currentRate = 0;

        public bool automatic = false;
        public float autoDurationInSeconds = 5;

        private void OnEnable() {
            string generatedName = "generated by " + GetType().Name;
            var generatedTranform = transform.Find(generatedName);
            generated = generatedTranform != null ? generatedTranform.gameObject : Instantiate(Follower, gameObject.transform);
            generated.name = generatedName;

            spline = GetComponent<Spline>(); 
        }

        void Update() {
            if (automatic)
            {
                rate += Time.deltaTime / autoDurationInSeconds;
                if(rate > 1)
                {
                    rate--;
                }
            }
            rate = Mathf.Clamp01(rate);
            _currentRate = rate * (spline.nodes.Count - 1);
            PlaceFollower();
        }

        private void PlaceFollower() {
            if (generated != null) {
                CurveSample sample = spline.GetSample(_currentRate);
                generated.transform.localPosition = sample.location;
                generated.transform.localRotation = sample.Rotation;
            }
        }
    }
}
